name: Primer workflow

on: push

jobs:
  tareas_hola_mundo:
    runs-on: ubuntu-latest 

    permissions:
      security-events: write

    steps:
      - 
        name: Bajase codigo
        uses: actions/checkout@v4
      - 
        name: Probar codigo
        run: python3 main.py

      - name: Aaaa
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: eneko/holamundo:latest
