name: Primer workflow

on: push

jobs:
  tareas_hola_mundo:
    runs-on: ubuntu-latest 

    permissions:
      security-events: write

    steps:
      - 
        name: Bajase codigo
        uses: actions/checkout@v4
      - 
        name: Probar codigo
        run: python3 main.py
        
      -
        name: Login to Docker Hub
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
